# 1 Getting data - webscraping 

# DID NOT MANAGE ANEW ... DRIT I DET !! (evt helt til sist...)

setwd("C:/Users/lse043/OneDrive - University of Bergen/Documents/0 PhD PROJECT/PAPER 2 'Strategies'/Ghana_RTI_media_advocacy")

library(readtext)
####Getting pages:####
library(rvest) #to get data
library(httr) #to set my user-agent string, be polite and say who I am
library(xml2)
library(selectr)
library(magrittr)
library(purrr) #henger visst sammen med rvest
library(readr) #henger visst sammen med rvest

# first, one page: 

#### 1.3.1 Scraping a typical page ####
https://www.ghanaweb.com/GhanaHomePage/NewsArchive/Does-Akufo-Addo-need-one-year-to-establish-an-RTI-board-Sam-George-asks-941377

BASE <- "https://www.ghanaweb.com/GhanaHomePage/"

url <- paste0(BASE, "NewsArchive/AG-explains-RTI-145838")
url

page <- read_html(url)  #typical page
page #take a peak

#page <- GET(url, add_headers('user-agent' = 'PhD researcher (Lisa.Selvik@uib.no)'))
#page
#page #take a peak

#Title: 
html_node(page, "h1")
html_text(html_node(page, "h1"))
title <- html_text(html_node(page, "h1"))

#Date: 
date <- html_text(html_node(page, ".floatLeft"))
date
typeof(date)    #and formatting (later)

#Text: 
#first, paragraphs:
paras <- html_text(html_nodes(page, "span+ p"))
length(paras)
head(paras) #checking
#then, into text: 
text <- paste(paras, collapse = " ")
text

#Putting it all together:
get_data <- function(url){
  Sys.sleep(0.5) # scrape slowwwwly
  page <- read_html(url)
  title <- html_text(html_node(page, 'h1'))
  date <- html_text(html_node(page, '.floatLeft')) # convert later
  paras <- html_text(html_nodes(page, 'span+ p'))
  text <- paste(paras, collapse = " ")
  list(title = title, date = date, text = text)
}

val_gw_p <- lapply(page, get_data)
val_gw_p

# the urls (see bottom of script)
urls_gw <- c(1:542)

BASE <- "https://www.ghanaweb.com/GhanaHomePage/"
for (i in 1:length(urls_gw)){urls_gw[[i]]<-paste(BASE,urls_gw[[i]],sep="")}
urls_gw

#scarping: 

pgs <- paste0(urls_gw)
pgs

val_gw <- lapply(pgs, get_data)

#Trying the GET w/ user agent ID:
get_data <- function(url){
  Sys.sleep(0.5) # scrape slowwwwly
  page <- GET(url, add_headers('user-agent' = 'PhD researcher (Lisa.Selvik@uib.no)'))
  title <- html_text(html_node(page, 'h1'))
  date <- html_text(html_node(page, '.floatLeft')) # convert later
  paras <- html_text(html_nodes(page, 'span+ p'))
  text <- paste(paras, collapse = " ")
  list(title = title, date = date, text = text)
}


# ================================================================================

# individual urls:
urls_gw[1] <- "NewsArchive/Does-Akufo-Addo-need-one-year-to-establish-an-RTI-board-Sam-George-asks-941377"
urls_gw[2] <- "NewsArchive/Designated-RTI-officers-undergo-training-896626"
urls_gw[3] <- "NewsArchive/Your-lawyers-had-no-business-responding-to-request-for-information-Ayenini-fires-EC-873181"
urls_gw[4] <- "NewsArchive/EC-gave-a-very-bogus-response-Ernest-Norgbey-869728"
urls_gw[5] <- "NewsArchive/Some-institutions-implementing-RTI-slowly-Oppong-Nkrumah-861604"
urls_gw[6] <- "politics/A-look-back-into-some-political-activities-in-2019-829729"
urls_gw[7] <- "NewsArchive/Ghana-in-365-days-Kwame-Gyan-s-highlights-of-Ghana-in-2019-824500"
urls_gw[8] <- "NewsArchive/RTI-Act-will-reduce-rumour-mongering-Oppong-Nkrumah-794666"
urls_gw[9] <- "NewsArchive/RTI-Act-will-reduce-rumour-mongering-Oppong-Nkrumah-794725"
urls_gw[10] <- "NewsArchive/Parliament-is-incapacitated-RTI-Coalition-chair-785148"
urls_gw[11] <- "NewsArchive/Do-not-fill-RTI-Secretariat-with-party-boys-Akoto-Ampaw-cautions-784548"
urls_gw[12] <- "NewsArchive/Do-not-fill-RTI-Secretariat-with-party-boys-Akoto-Ampaw-cautions-784628"
urls_gw[13] <- "NewsArchive/Government-to-appoint-Information-Commissioner-784254"
urls_gw[14] <- "NewsArchive/Government-to-appoint-Information-Commissioner-784262"
urls_gw[15] <- "NewsArchive/RTI-commission-not-for-party-members-Akoto-Ampaw-warns-Akufo-Addo-783687"
urls_gw[16] <- "NewsArchive/MPs-feel-anti-corruption-laws-will-haunt-them-thus-delay-in-passage-Short-780327"
urls_gw[17] <- "politics/NDC-s-presser-on-corruption-tasteless-vague-NPP-780420"
urls_gw[18] <- "politics/Stop-being-friendly-with-a-party-that-shit-bombs-you-NPP-warns-media-against-NDC-780506"
urls_gw[19] <- "NewsArchive/Coalition-on-the-RTI-honours-stakeholders-767883"
urls_gw[20] <- "NewsArchive/Akoto-Ampaw-hails-Bagbin-Joe-Wise-for-RTI-passage-765989"
urls_gw[21] <- "NewsArchive/RTI-law-Oppong-Nkrumah-s-plans-good-but-ambitious-Akoto-Ampaw-765929"
urls_gw[22] <- "NewsArchive/Define-role-of-MPs-to-reduce-burden-on-them-Abdallah-Banda-757243"
urls_gw[23] <- "NewsArchive/Special-Prosecutor-is-working-Bawumia-755223"
urls_gw[24] <- "NewsArchive/Akufo-Addo-attached-urgency-to-RTI-bill-Coalition-749667"
urls_gw[25] <- "NewsArchive/Passing-of-RTI-law-is-a-plus-for-President-Akufo-Addo-749086"
urls_gw[26] <- "NewsArchive/Don-t-shower-all-the-praises-on-Akufo-Addo-over-passage-ascent-of-RTI-Inusah-Fuseini-748480"
urls_gw[27] <- "NewsArchive/Akufo-Addo-assents-to-RTI-bill-748063"
urls_gw[28] <- "NewsArchive/Akufo-Addo-signs-RTI-Bill-into-Law-748069"
urls_gw[29] <- "NewsArchive/Nana-Addo-to-assent-to-RTI-Act-today-747981"
urls_gw[30] <- "NewsArchive/RTI-to-boost-corruption-fight-in-2020-Akufo-Addo-asserts-as-he-signs-bill-into-law-748098"
urls_gw[31] <- "NewsArchive/Move-away-from-reporting-propaganda-Franklin-Cudjoe-to-journalists-743794"
urls_gw[32] <- "NewsArchive/RTI-Bill-yet-to-be-forwarded-to-Presidency-a-month-after-parliamentary-approval-742796"
urls_gw[33] <- "NewsArchive/President-yet-to-receive-RTI-law-one-month-after-passage-742673"
urls_gw[34] <- "NewsArchive/Prepare-for-RTI-coalition-to-state-institutions-739280"
urls_gw[35] <- "NewsArchive/Speed-up-work-on-RTI-Coalition-to-Parliament-739247"
urls_gw[36] <- "NewsArchive/We-don-t-want-any-ignorant-person-as-Commissioner-RTI-Coalition-warns-Akufo-Addo-739057"
urls_gw[37] <- "features/An-open-letter-to-the-Asante-Akyem-South-Member-Of-Parliament-735526"
urls_gw[38] <- "politics/No-political-party-deserves-praises-for-RTI-law-Asiedu-Nketia-734472"
urls_gw[39] <- "NewsArchive/Government-open-to-more-funding-options-for-RTI-support-Oppong-Nkrumah-734236"
urls_gw[40] <- "NewsArchive/NCCE-lauds-Parliament-for-passing-the-RTI-Bill-734201"
urls_gw[41] <- "NewsArchive/RTI-law-will-help-CHRAJ-actualise-its-vision-Director-734179"
urls_gw[42] <- "NewsArchive/Bow-your-heads-in-shame-for-delaying-RTI-passage-Casely-Hayford-to-Parliament-734333"
urls_gw[43] <- "NewsArchive/PPP-lauds-government-Parliament-for-passing-RTI-734110"
urls_gw[44] <- "politics/Thank-you-for-passing-RTI-when-others-couldn-t-PPP-to-gov-t-Parliament-734067"
urls_gw[45] <- "NewsArchive/Ghana-RTI-Bill-After-20-years-of-tsaskele-parliament-finally-pass-Right-to-Information-Bill-733786"
urls_gw[46] <- "NewsArchive/Government-blows-over-GHC2-2m-on-vegetable-oil-Chief-Biney-alleges-733673"
urls_gw[47] <- "NewsArchive/Let-s-police-implementation-of-RTI-Law-MFWA-urges-stakeholders-733845"
urls_gw[48] <- "NewsArchive/My-views-on-RTI-law-hasn-t-changed-KT-Hammond-733692"
urls_gw[49] <- "NewsArchive/RTI-implementation-Don-t-wait-to-couch-another-batch-of-flimsy-excuses-next-year-Anyenini-733758"
urls_gw[50] <- "NewsArchive/RTI-law-is-the-solution-to-corruption-Deputy-Minister-733790"
urls_gw[51] <- "NewsArchive/RTI-law-not-just-about-fighting-corruption-Ayariga-733690"
urls_gw[52] <- "NewsArchive/RTI-Passage-It-s-been-a-long-journey-Kweku-Baako-733772"
urls_gw[53] <- "NewsArchive/Coalition-welcomes-passage-of-RTI-Bill-asks-for-swift-presidential-assent-733527"
urls_gw[54] <- "NewsArchive/Delegating-supervision-of-RTI-to-Information-Minister-wrong-Haruna-733555"
urls_gw[55] <- "NewsArchive/Delegating-supervision-of-RTI-to-Information-Minister-wrong-Haruna-733584"
urls_gw[56] <- "NewsArchive/Ghana-s-RTI-law-one-of-the-best-in-the-world-Bagbin-733418"
urls_gw[57] <- "NewsArchive/Media-coalition-unhappy-over-controversial-clause-in-RTI-Bill-733408"
urls_gw[58] <- "NewsArchive/Ministers-with-girlfriends-must-be-careful-Allotey-Jacobs-on-RTI-Bill-733612"
urls_gw[59] <- "NewsArchive/MPs-don-t-know-cost-of-implementing-RTI-law-Abdallah-733581"
urls_gw[60] <- "NewsArchive/MP-s-claims-on-our-proposed-amendments-to-RTI-bill-false-Coalition-733569"
urls_gw[61] <- "NewsArchive/NPP-government-has-made-corruption-an-attractive-venture-Sammy-Gyamfi-733449"
urls_gw[62] <- "NewsArchive/RTI-Bill-You-don-t-obstruct-and-take-credit-for-it-s-passage-Minority-Leader-to-gov-t-733620"
urls_gw[63] <- "NewsArchive/RTI-law-I-don-t-doubt-that-Akufo-Addo-genuinely-wanted-to-pass-this-bill-Samson-Anyenini-733611"
urls_gw[64] <- "NewsArchive/RTI-passage-Don-t-jubilate-yet-Karikari-to-journalists-733464"
urls_gw[65] <- "NewsArchive/Swiftly-sign-RTI-bill-as-you-promised-Coalition-to-Akufo-Addo-733500"
urls_gw[66] <- "NewsArchive/We-ll-resist-attempts-to-hide-information-under-national-security-Bentil-733467"
urls_gw[67] <- "NewsArchive/Why-fuss-over-passage-of-RTI-law-when-you-were-literally-forced-Government-parliament-quizzed-733586"
urls_gw[68] <- "NewsArchive/Why-fuss-over-passage-of-RTI-law-when-you-were-literally-forced-Government-parliament-quizzed-733587"
urls_gw[69] <- "NewsArchive/Parliament-approves-RTI-Bill-733350"
urls_gw[70] <- "NewsArchive/Parliament-finally-passes-RTI-Bill-733348"
urls_gw[71] <- "NewsArchive/Government-begins-preparation-towards-implementation-of-RTI-Minister-732850"
urls_gw[72] <- "NewsArchive/Government-starts-preparing-road-map-for-RTI-implementation-732928"
urls_gw[73] <- "NewsArchive/RTI-Government-begins-implementation-process-ahead-of-passage-Oppong-Nkrumah-732894"
urls_gw[74] <- "NewsArchive/Government-to-commence-preparatory-work-ahead-of-RTI-Bill-passage-Minister-732812"
urls_gw[75] <- "NewsArchive/Passage-of-RTI-delayed-again-732759"
urls_gw[76] <- "NewsArchive/RTI-Bill-to-be-law-on-Tuesday-732506"
urls_gw[77] <- "NewsArchive/Parliament-suspends-passage-of-RTI-Bill-732290"
urls_gw[78] <- "NewsArchive/Proposed-amendments-not-to-blame-for-delay-of-passage-of-RTI-Bill-Coalition-732436"
urls_gw[79] <- "NewsArchive/RTI-Bill-to-be-passed-next-week-Tuesday-Kyei-Mensah-Bonsu-732453"
urls_gw[80] <- "NewsArchive/RTI-New-amendments-presented-by-CSOs-delaying-passage-of-Bill-MP-732393"
urls_gw[81] <- "NewsArchive/Speaker-orders-removal-of-RTI-bill-from-Order-Paper-732380"
urls_gw[82] <- "NewsArchive/Today-at-the-newsstands-732318"
urls_gw[83] <- "NewsArchive/Blame-CSOs-for-RTI-passage-delays-Ben-Abdalla-732178"
urls_gw[84] <- "NewsArchive/RTI-bill-may-be-passed-on-Friday-Mensah-Bonsu-732014"
urls_gw[85] <- "NewsArchive/Speaker-orders-removal-of-RTI-bill-from-Order-Paper-732149"
urls_gw[86] <- "NewsArchive/We-re-not-to-blame-for-delays-in-passage-of-RTI-Bill-Parliament-732193"
urls_gw[87] <- "NewsArchive/Ghanaian-MPs-only-good-at-approving-car-loans-Prophet-Kofi-Oduro-731192"
urls_gw[88] <- "NewsArchive/RTI-Bill-Ghanaian-MPs-only-good-at-approving-car-loans-Preacher-blasts-lawmakers-731011"
urls_gw[89] <- "NewsArchive/RTI-Bill-passage-We-have-a-defective-parliament-Kofi-Bentil-728245"
urls_gw[90] <- "NewsArchive/Research-stating-GH-750m-price-tag-for-RTI-implementation-flawed-CDD-726512"
urls_gw[91] <- "NewsArchive/Implementing-RTI-pegged-at-GHc750m-for-five-years-Report-726336"
urls_gw[92] <- "NewsArchive/RTI-Bill-implementation-to-cost-750m-726165"
urls_gw[93] <- "NewsArchive/I-ll-happily-sign-RTI-Bill-into-law-Akufo-Addo-725251"
urls_gw[94] <- "NewsArchive/Highlights-of-Akufo-Addo-s-SONA-725135"
urls_gw[95] <- "NewsArchive/Latest-amendment-to-RTI-Bill-problematic-Coalition-724447"
urls_gw[96] <- "NewsArchive/BoG-seeks-RTI-Bill-review-to-protect-sensitive-data-Inusah-Fuseini-723266"
urls_gw[97] <- "NewsArchive/RTI-law-will-take-effect-in-2020-after-passage-Majority-Leader-723181"
urls_gw[98] <- "NewsArchive/Today-at-the-newsstands-723268"
urls_gw[99] <- "NewsArchive/Parliament-approves-postponed-start-date-for-RTI-Bill-723083"
urls_gw[100] <- "entertainment/Don-t-blame-bloggers-who-write-junk-stories-Sammy-Flex-721657"
urls_gw[101] <- "entertainment/Don-t-blame-bloggers-for-writing-junk-stories-Sammy-Flex-721538"
urls_gw[102] <- "features/Djokoto-s-Diary-Get-the-RTI-bill-through-721301"
urls_gw[103] <- "NewsArchive/Parliament-urged-to-pass-credible-RTI-bill-720882"
urls_gw[104] <- "NewsArchive/CSOs-to-meet-Parliament-over-delay-in-passage-of-RTI-Bill-720508"
urls_gw[105] <- "NewsArchive/Minority-against-RTI-implementation-delay-720596"
urls_gw[106] <- "NewsArchive/Today-at-the-news-stands-720520"
urls_gw[107] <- "NewsArchive/Coalition-pleads-with-Parliament-to-pass-credible-RTI-bill-720423"
urls_gw[108] <- "NewsArchive/We-can-t-pass-RTI-Bill-this-year-due-to-financial-challenges-Majority-Leader-720289"
urls_gw[109] <- "NewsArchive/Contention-over-commencement-date-delaying-passage-of-RTI-bill-MP-719565"
urls_gw[110] <- "NewsArchive/Today-at-the-News-stands-719611"
urls_gw[111] <- "NewsArchive/NPP-MP-seeks-1-year-grace-period-after-RTI-passage-719536"
urls_gw[112] <- "NewsArchive/Parliament-to-prioritise-RTI-bill-719138"
urls_gw[113] <- "NewsArchive/RTI-Bill-kidnappings-in-focus-as-Parliament-returns-from-recess-today-718943"
urls_gw[114] <- "NewsArchive/Oil-boom-fueling-kidnappings-in-Western-Region-Boakye-Djan-717486"
urls_gw[115] <- "NewsArchive/RTI-Bill-to-be-passed-when-Parliament-resumes-716804"
urls_gw[116] <- "NewsArchive/I-am-not-comfortable-with-RTI-Bill-Mampong-MP-713191"
urls_gw[117] <- "NewsArchive/LIVESTREAMING-Newsfile-on-JoyNews-711784"
urls_gw[118] <- "NewsArchive/We-won-t-back-off-expect-real-pressure-in-2019-RTI-coalition-replies-Speaker-711425"
urls_gw[119] <- "NewsArchive/RTI-Bill-Leave-us-alone-Speaker-to-civil-society-711310"
urls_gw[120] <- "NewsArchive/Media-Coalition-replies-Oquaye-s-criticism-of-CSOs-on-RTI-Bill-vows-to-pile-more-pressure-711036"
urls_gw[121] <- "NewsArchive/RTI-bill-will-be-passed-by-end-of-February-2019-Oquaye-711015"
urls_gw[122] <- "features/What-happened-to-Kufour-s-Zero-Tolerance-Policy-96356"
urls_gw[123] <- "NewsArchive/Leave-us-alone-to-finish-up-on-tricky-RTI-bill-Speaker-to-CSOs-710849"
urls_gw[124] <- "NewsArchive/Leave-us-alone-to-finish-up-on-tricky-RTI-bill-Speaker-to-CSOs-710911"
urls_gw[125] <- "NewsArchive/Leave-us-alone-to-deal-with-tricky-RTI-bill-Speaker-710899"
urls_gw[126] <- "NewsArchive/Speaker-slams-CSOs-for-piling-pressure-to-get-RTI-Bill-passed-710969"
urls_gw[127] <- "NewsArchive/We-ll-pass-the-RTI-in-February-next-year-after-a-professional-job-done-Speaker-710839"
urls_gw[128] <- "NewsArchive/Support-our-efforts-to-promote-press-freedom-Information-Minister-urges-new-UNESCO-Country-boss-710519"
urls_gw[129] <- "NewsArchive/Importance-of-RTI-law-supersedes-fight-against-corruption-Elvis-Darko-710427"
urls_gw[130] <- "NewsArchive/Without-RTI-law-our-democracy-is-incomplete-CDD-710429"
urls_gw[131] <- "NewsArchive/Provide-updates-of-Nyantekyi-Jospong-alleged-corruption-investigations-GII-tasks-gov-t-709940"
urls_gw[132] <- "NewsArchive/RTI-bill-can-be-passed-in-four-days-Majority-Leader-709847"
urls_gw[133] <- "politics/ADI-demands-halt-and-reflection-over-RTI-bill-709568"
urls_gw[134] <- "features/Ace-Ankomah-writes-on-medical-drones-709010"
urls_gw[135] <- "features/Ace-Ankomah-writes-on-medical-drones-708465"
urls_gw[136] <- "NewsArchive/Approving-2019-budget-important-than-RTI-bill-Ben-Abdallah-708469"
urls_gw[137] <- "NewsArchive/National-security-stability-must-be-considered-before-RTI-Bill-passage-Kufuor-708471"
urls_gw[138] <- "NewsArchive/RTI-must-not-compromise-National-Security-Kufuor-708496"
urls_gw[139] <- "NewsArchive/Today-at-the-News-stands-708417"
urls_gw[140] <- "NewsArchive/You-can-t-set-a-trap-for-yourself-politicians-won-t-approve-RTI-Bill-Allotey-Jacobs-708436"
urls_gw[141] <- "NewsArchive/Be-wary-of-Ghana-s-security-before-passing-RTI-Ex-President-Kufuor-708337"
urls_gw[142] <- "NewsArchive/Government-s-handling-of-RTI-Bill-deeply-embarrassing-MFWA-708118"
urls_gw[143] <- "NewsArchive/Government-s-handling-of-RTI-Bill-deeply-embarrassing-MFWA-708183"
urls_gw[144] <- "NewsArchive/Bawumia-takes-over-in-fresh-RTI-deadline-as-Akufo-Addo-promise-fails-707891"
urls_gw[145] <- "NewsArchive/Bawumia-takes-over-in-fresh-RTI-deadline-as-Akufo-Addo-promise-fails-707919"
urls_gw[146] <- "NewsArchive/Parliament-suspends-formation-of-quorum-to-expedite-passage-of-RTI-707885"
urls_gw[147] <- "NewsArchive/Parliament-suspends-formation-of-quorum-to-expedite-passage-of-RTI-707725"
urls_gw[148] <- "NewsArchive/RTI-Bill-CSOs-worried-over-conflicting-information-from-Parliament-707847"
urls_gw[149] <- "NewsArchive/Today-at-the-News-stands-707757"
urls_gw[150] <- "NewsArchive/Ghanaians-urged-to-demand-accountability-as-a-matter-of-their-human-rights-707544"
urls_gw[151] <- "NewsArchive/Pass-RTI-Bill-before-you-go-on-recess-PPP-to-Parliament-707496"
urls_gw[152] <- "NewsArchive/RTI-Bill-may-enter-2019-Majority-Leader-707610"
urls_gw[153] <- "features/Samson-s-Take-RTI-Red-Friday-Just-pass-the-Bill-707096"
urls_gw[154] <- "NewsArchive/Parliament-to-pass-the-RTI-Bill-before-end-of-session-on-December-22-706936"
urls_gw[155] <- "NewsArchive/Parliament-to-push-passage-of-RTI-to-next-sitting-706690"
urls_gw[156] <- "NewsArchive/We-ll-pass-RTI-bill-in-January-2019-Kyei-Mensah-Bonsu-706695"
urls_gw[157] <- "NewsArchive/We-may-pass-RTI-bill-by-end-of-December-Kyei-Mensah-Bonsu-706702"
urls_gw[158] <- "NewsArchive/No-discrimination-against-PWDs-in-Parliament-First-Deputy-Speaker-706374"
urls_gw[159] <- "NewsArchive/RTI-Bill-won-t-pass-in-2018-Executive-not-hungry-enough-Sam-George-705930"
urls_gw[160] <- "NewsArchive/Back-from-demo-retirement-Baako-readies-for-RTI-fight-705488"
urls_gw[161] <- "NewsArchive/Parliament-does-not-discriminate-against-PWDs-Joseph-Osei-Owusu-705834"
urls_gw[162] <- "NewsArchive/I-will-suspend-my-suspension-of-demo-Baako-readies-for-RTI-fight-705434"
urls_gw[163] <- "NewsArchive/PLAYBACK-Newsfile-on-JoyNews-705374"
urls_gw[164] <- "NewsArchive/PLAYBACK-Newsfile-on-JoyNews-705416"
urls_gw[165] <- "NewsArchive/PLAYBACK-Newsfile-on-JoyNews-705686"
urls_gw[166] <- "NewsArchive/Passage-of-RTI-law-Media-Coalition-CSOs-kick-start-RedFriday-campaign-705209"
urls_gw[167] <- "NewsArchive/We-ll-sue-government-if-RTI-bill-is-passed-with-exemptions-Akoto-Ampaw-705240"
urls_gw[168] <- "NewsArchive/RTIRedFriday-starts-today-704878"
urls_gw[169] <- "NewsArchive/Disabled-man-refused-entry-to-parliament-because-he-can-t-rise-to-show-respect-to-Speaker-704956"
urls_gw[170] <- "features/Why-RTI-is-a-test-of-Akufo-Addo-s-integrity-and-parliament-s-usefulness-704892"
urls_gw[171] <- "NewsArchive/Majority-Leader-not-rallying-MPs-for-RTI-Bill-Sam-George-704624"
urls_gw[172] <- "NewsArchive/Passing-RTI-bill-is-to-benefit-government-Kofi-Abotsi-704656"
urls_gw[173] <- "NewsArchive/CSOs-media-declare-RTI-Red-Friday-protest-starting-November-30-703956"
urls_gw[174] <- "features/Dr-Kojo-Asante-writes-Government-won-t-come-to-a-halt-if-you-pass-RTI-701901"
urls_gw[175] <- "NewsArchive/Issue-an-apology-to-Elvis-Darko-Excellent-Ghana-appeals-to-Akufo-Addo-701315"
urls_gw[176] <- "NewsArchive/RTI-Bill-How-the-police-dealt-with-Media-Coalition-701272"
urls_gw[177] <- "NewsArchive/RTI-coalition-member-released-after-arrest-in-Parliament-701324"
urls_gw[178] <- "NewsArchive/Today-at-the-news-stands-701330"
urls_gw[179] <- "NewsArchive/Elvis-Darko-explains-how-and-why-he-was-arrested-701198"
urls_gw[180] <- "NewsArchive/RTI-campaign-Finder-newspaper-editor-explains-how-and-why-he-was-arrested-701238"
urls_gw[181] <- "NewsArchive/The-Finder-editor-arrested-in-Parliament-for-picketing-701087"
urls_gw[182] <- "NewsArchive/Update-The-Finder-editor-released-701137"
urls_gw[183] <- "NewsArchive/Members-of-parliament-to-initiate-bills-700759"
urls_gw[184] <- "NewsArchive/Members-of-Parliament-to-initiate-bills-700854"
urls_gw[185] <- "NewsArchive/Parliament-a-danger-to-RTI-Bill-Akoto-Ampaw-700741"
urls_gw[186] <- "NewsArchive/RTI-Bill-will-be-passed-before-close-of-2018-Speaker-of-Parliament-stresses-700667"
urls_gw[187] <- "NewsArchive/Saying-I-m-ignorant-of-RTI-Bill-below-the-belt-K-T-Hammond-700696"
urls_gw[188] <- "NewsArchive/I-stand-by-comments-on-RTI-Bill-criticize-me-if-you-want-K-T-Hammond-700659"
urls_gw[189] <- "NewsArchive/OccupyGhana-educates-backward-NPP-MP-on-Right-to-Information-Bill-700363"
urls_gw[190] <- "NewsArchive/Over-200-MPs-not-serious-with-passage-of-RTI-Bill-Media-Coalition-700385"
urls_gw[191] <- "NewsArchive/Parliament-frustrating-passage-of-RTI-Bill-over-200-members-absent-Media-Coalition-on-RTI-700519"
urls_gw[192] <- "NewsArchive/Parliament-not-serious-about-passing-RTI-Bill-RTI-Coalition-700222"
urls_gw[193] <- "NewsArchive/Today-at-the-news-stands-700302"
urls_gw[194] <- "NewsArchive/Over-200-MPs-abandon-RTI-Bill-Media-Coalition-700174"
urls_gw[195] <- "NewsArchive/RTI-Bill-will-be-passed-before-close-of-2018-Speaker-of-Parliament-stresses-700206"
urls_gw[196] <- "features/Criminalising-political-office-holding-in-our-politics-699722"
urls_gw[197] <- "features/Parliament-and-the-right-to-information-bill-699725"
urls_gw[198] <- "NewsArchive/Journalists-question-MPs-for-running-away-from-their-core-business-699050"
urls_gw[199] <- "NewsArchive/Parliament-suspends-RTI-Bill-for-the-second-time-698859"
urls_gw[200] <- "features/Is-there-a-panacea-at-all-for-Corruption-697914"
urls_gw[201] <- "features/Is-there-a-panacea-at-all-for-corruption-697834"
urls_gw[202] <- "features/RTI-Bill-Self-serving-MPs-must-know-citizens-real-ultimate-power-697829"
urls_gw[203] <- "politics/Show-commitment-to-passage-of-RTI-bill-stop-introducing-other-bills-NDC-MP-to-Gov-t-697680"
urls_gw[204] <- "NewsArchive/Benefits-of-RTI-goes-beyond-politics-Coalition-Coordinator-697545"
urls_gw[205] <- "NewsArchive/We-re-committed-to-RTI-Bill-we-ll-pass-it-soon-Kpemka-697315"
urls_gw[206] <- "NewsArchive/Corrupt-politicians-afraid-to-pass-RTI-bill-NCCE-officer-697413"
urls_gw[207] <- "NewsArchive/Government-will-no-longer-have-secrets-if-we-pass-RTI-Bill-K-T-Hammond-697190"
urls_gw[208] <- "NewsArchive/K-T-Hammond-an-apology-of-an-MP-RTI-Coalition-697192"
urls_gw[209] <- "NewsArchive/RTI-Bill-recipe-for-disaster-K-T-Hammond-697096"
urls_gw[210] <- "NewsArchive/RTI-Media-Coalition-to-begin-publishing-names-of-absentee-MPs-in-media-today-697102"
urls_gw[211] <- "NewsArchive/RTI-Media-Coalition-to-begin-publishing-names-of-absentee-MPs-in-media-today-697062"
urls_gw[212] <- "NewsArchive/We-won-t-rush-passage-of-RTI-Bill-K-T-Hammond-697094"
urls_gw[213] <- "NewsArchive/Don-t-pressurise-Parliament-over-RTI-Bill-Majority-leader-696776"
urls_gw[214] <- "NewsArchive/Passage-of-RTI-bill-a-recipe-for-disaster-KT-Hammond-696957"
urls_gw[215] <- "NewsArchive/Today-at-the-news-stands-696766"
urls_gw[216] <- "NewsArchive/Campaign-to-get-RTI-bill-passed-intensifies-despite-setback-at-Parliament-696584"
urls_gw[217] <- "NewsArchive/Journalists-kicked-out-of-Parliament-for-wearing-T-Shirts-696572"
urls_gw[218] <- "NewsArchive/Journalists-to-storm-Parliament-Tuesday-to-push-for-RTI-Bill-passage-696426"
urls_gw[219] <- "NewsArchive/Media-fight-for-RTI-bill-misplaced-priority-Sam-George-696612"
urls_gw[220] <- "NewsArchive/Pass-RTI-Bill-or-face-our-wrath-Media-Coalition-on-RTI-Bill-to-parliament-696333"
urls_gw[221] <- "NewsArchive/RTI-Bill-Media-practitioners-take-on-parliament-696334"
urls_gw[222] <- "NewsArchive/Coalition-calls-for-immediate-passage-of-Right-to-Information-Bill-139422"
urls_gw[223] <- "NewsArchive/Public-institutions-worst-culprits-in-statistics-production-693562"
urls_gw[224] <- "regional/Advocates-call-for-the-intensification-of-education-on-RTI-bill-692736"
urls_gw[225] <- "NewsArchive/Read-and-Understand-RTI-Bill-before-it-is-passed-Oppong-Nkrumah-to-GIJ-Students-690708"
urls_gw[226] <- "NewsArchive/Read-and-understand-RTI-Bill-before-it-is-passed-Oppong-Nkrumah-to-GIJ-Students-690761"
urls_gw[227] <- "politics/Anti-corruption-institutions-lack-resources-CDD-690686"
urls_gw[228] <- "NewsArchive/Government-is-working-gradually-towards-the-election-of-MMDCES-Pius-Hadzide-690309"
urls_gw[229] <- "NewsArchive/NDC-didn-t-pass-RTI-Bill-because-NPP-was-uncomfortable-Ablakwa-690467"
urls_gw[230] <- "NewsArchive/NPP-NDC-sabotaging-RTI-Bill-CDD-689948"
urls_gw[231] <- "NewsArchive/Pass-the-RTI-Bill-into-law-now-CDD-688858"
urls_gw[232] <- "NewsArchive/Parliament-in-retrospect-673809"
urls_gw[233] <- "NewsArchive/RTI-Bill-Parliament-s-snail-s-pace-disappointing-Coalition-673210"
urls_gw[234] <- "NewsArchive/We-ll-speed-up-passage-of-RTI-bill-at-next-sitting-Speaker-673064"
urls_gw[235] <- "NewsArchive/RTI-Bill-cannot-be-passed-now-Mensah-Bonsu-671923"
urls_gw[236] <- "features/Samson-s-Take-RTI-delete-clause-13-media-failing-citizens-668629"
urls_gw[237] <- "features/Samson-s-Take-Dear-MPs-pass-a-credible-RTI-law-664732"
urls_gw[238] <- "politics/Participants-call-on-MPs-to-pass-a-credible-RTI-bill-664039"
urls_gw[239] <- "NewsArchive/Review-RTI-clause-that-shields-information-from-Presidency-RTI-Coalition-663546"
urls_gw[240] <- "NewsArchive/To-fight-corruption-effectively-MPs-must-not-be-Ministers-RTI-Chairman-663209"
urls_gw[241] <- "NewsArchive/Government-urged-to-pass-RTI-to-fight-corruption-662305"
urls_gw[242] <- "NewsArchive/Media-urged-to-intensify-advocacy-for-passage-Bill-661887"
urls_gw[243] <- "NewsArchive/Current-RTI-Bill-has-some-useless-clauses-Kwesi-Boateng-Assumeng-661412"
urls_gw[244] <- "politics/Participants-in-Municipal-sanitation-day-pilfering-tools-660241"
urls_gw[245] <- "NewsArchive/RTI-Coalition-accuses-parliament-of-rejecting-its-input-659877"
urls_gw[246] <- "NewsArchive/CSOs-pray-Ghana-s-RTI-Bill-meets-global-standard-658920"
urls_gw[247] <- "NewsArchive/RTI-Bill-taken-through-second-reading-658478"
urls_gw[248] <- "NewsArchive/Journalists-urged-to-help-educate-public-on-RTI-bill-658346"
urls_gw[249] <- "NewsArchive/Parliament-to-debate-RTI-bill-next-week-654536"
urls_gw[250] <- "NewsArchive/Improved-RTI-bill-to-be-laid-before-parliament-next-week-Haruna-Iddrisu-654355"
urls_gw[251] <- "NewsArchive/Threat-to-media-freedom-coming-from-non-state-actors-Prof-Gadzekpo-654243"
urls_gw[252] <- "NewsArchive/PRAAD-crucial-to-Right-To-Information-OccupyGhana-653729"
urls_gw[253] <- "features/Bills-Bills-Bills-652623"
urls_gw[254] <- "NewsArchive/Buts-ifs-maybes-continue-as-RTI-bill-misses-government-business-list-in-Parliament-652126"
urls_gw[255] <- "NewsArchive/Speed-up-RTI-Bill-Oquaye-to-MPs-652078"
urls_gw[256] <- "NewsArchive/RTI-Bill-will-trigger-inactive-laws-to-work-Majority-leader-650158"
urls_gw[257] <- "NewsArchive/RTI-law-essential-for-good-governance-Gloria-Akuffo-649970"
urls_gw[258] <- "NewsArchive/500-sign-petition-to-demand-passage-of-RTI-bill-649506"
urls_gw[259] <- "NewsArchive/Parliament-urged-to-pass-RTI-Bill-to-promote-transparency-649657"
urls_gw[260] <- "NewsArchive/Parliament-to-hold-conference-on-RTI-bill-May-8-649035"
urls_gw[261] <- "NewsArchive/Fake-Journalists-ruining-the-profession-GJA-President-laments-649027"
urls_gw[262] <- "features/Fourth-estate-of-the-realm-under-attack-648725"
urls_gw[263] <- "features/Citizenship-and-Press-Freedom-is-meaningless-without-a-credible-Right-to-Information-Law-648374"
urls_gw[264] <- "NewsArchive/Government-criticised-at-World-Press-Freedom-celebration-for-failing-to-pass-RTI-Bill-648346"
urls_gw[265] <- "NewsArchive/Don-t-trade-your-integrity-for-headlines-Hamid-to-journalists-648199"
urls_gw[266] <- "NewsArchive/RTI-Bill-attacks-on-journalists-remain-top-concerns-as-Ghana-marks-Press-Freedom-Day-648055"
urls_gw[267] <- "NewsArchive/Parliament-withdraws-RTI-bill-again-for-not-being-urgent-in-nature-646816"
urls_gw[268] <- "NewsArchive/RTI-bill-re-laid-in-Parliament-646873"
urls_gw[269] <- "NewsArchive/RTI-bill-re-laid-in-Parliament-646874"
urls_gw[270] <- "NewsArchive/Help-me-to-fight-corruption-Akufo-Addo-begs-CSOs-642193"
urls_gw[271] <- "NewsArchive/Parliament-calls-for-contributions-to-the-RTI-Bill-640574"
urls_gw[272] <- "NewsArchive/Work-on-RTI-bill-during-recess-Kyei-Mensah-Bonsu-urges-MPs-638437"
urls_gw[273] <- "NewsArchive/RTI-will-be-law-by-end-of-2018-Mustapha-Hamid-638167"
urls_gw[274] <- "NewsArchive/RTI-Bill-We-ve-shown-great-commitment-Mustapha-Hamid-637946"
urls_gw[275] <- "NewsArchive/RTI-will-be-law-by-end-of-2018-Hamid-637915"
urls_gw[276] <- "NewsArchive/Treat-RTI-bill-with-same-speed-as-defence-deal-Cudjoe-637446"
urls_gw[277] <- "NewsArchive/20-year-old-RTI-Bill-likely-to-be-laid-in-Parliament-today-637127"
urls_gw[278] <- "NewsArchive/Government-lays-RTI-Bill-amid-opposition-from-Minority-637344"
urls_gw[279] <- "features/Is-Bawumia-really-an-insider-in-the-Akufo-Addo-government-637202"
urls_gw[280] <- "NewsArchive/RTI-Bill-can-t-be-passed-before-today-s-recess-Majority-Leader-637139"
urls_gw[281] <- "NewsArchive/RTI-Bill-finally-laid-before-Parliament-637227"
urls_gw[282] <- "NewsArchive/Today-at-the-newsstands-637092"
urls_gw[283] <- "NewsArchive/Your-integrity-is-at-stake-RTI-Coalition-to-Akufo-Addo-637169"
urls_gw[284] <- "NewsArchive/Your-integrity-is-at-stake-RTI-Coalition-to-Akufo-Addo-637173"
urls_gw[285] <- "NewsArchive/Cabinet-yet-to-approve-RTI-Bill-Mensah-Bonsu-contradicts-Bawumia-636978"
urls_gw[286] <- "NewsArchive/Cabinet-yet-to-approve-RTI-Bill-Mensah-Bonsu-636939"
urls_gw[287] <- "NewsArchive/Don-t-blame-Akufo-Addo-for-late-passage-of-RTI-Bill-Manhyia-North-MP-636733"
urls_gw[288] <- "NewsArchive/Governments-scared-of-RTI-Bill-Obed-Asamoah-636859"
urls_gw[289] <- "NewsArchive/Lay-RTI-Bill-before-Parliament-rises-Coalition-636895"
urls_gw[290] <- "NewsArchive/Redeem-your-pledge-RTI-Action-Campaign-Group-to-Government-636975"
urls_gw[291] <- "features/The-Right-To-Information-Bill-Let-my-say-have-its-way-636698"
urls_gw[292] <- "NewsArchive/Cabinet-approves-RTI-Bill-636118"
urls_gw[293] <- "NewsArchive/Parliament-can-pass-RTI-Bill-in-4-days-under-Certificate-of-Emergency-Ayariga-635963"
urls_gw[294] <- "NewsArchive/President-wasn-t-well-informed-we-can-t-pass-RTI-this-week-Inusah-Fuseini-636097"
urls_gw[295] <- "NewsArchive/Today-at-the-newsstands-636028"
urls_gw[296] <- "NewsArchive/Cabinet-approves-RTI-bill-set-for-Parliament-Vice-President-635941"
urls_gw[297] <- "NewsArchive/Cabinet-has-approved-RTI-Bill-Bawumia-635746"
urls_gw[298] <- "NewsArchive/Cabinet-okays-RTI-Bill-set-to-be-sent-to-Parliament-this-week-635796"
urls_gw[299] <- "NewsArchive/Lack-of-RTI-law-not-a-problem-Prof-Asare-635794"
urls_gw[300] <- "NewsArchive/Pressure-mounts-on-Parliament-to-pass-RTI-Bill-635912"
urls_gw[301] <- "NewsArchive/Read-RTI-bill-and-stop-saying-it-has-a-problem-Samson-Lardy-to-Speaker-others-635953"
urls_gw[302] <- "NewsArchive/Revised-RTI-Bill-approved-forwarded-to-Parliament-Bawumia-635771"
urls_gw[303] <- "NewsArchive/RTI-Bill-meaningless-without-covering-private-sector-Mike-Oquaye-635667"
urls_gw[304] <- "NewsArchive/RTI-bill-No-group-has-threatened-President-Anyenini-635732"
urls_gw[305] <- "NewsArchive/RTI-Coalition-hits-the-streets-over-passage-of-RTI-Bill-635861"
urls_gw[306] <- "NewsArchive/RTI-will-ensure-journalism-without-speculation-Sampson-Lardy-Anyenini-635954"
urls_gw[307] <- "NewsArchive/Trending-GH-Pass-RTI-Bill-now-Ghanaians-back-RTI-Coalition-635788"
urls_gw[308] <- "NewsArchive/Former-MP-accuses-Majority-Leader-of-disrupting-passage-of-RTI-bill-635346"
urls_gw[309] <- "NewsArchive/No-group-can-threaten-parliament-to-pass-RTI-Bill-Deputy-Speaker-635484"
urls_gw[310] <- "NewsArchive/Kyei-Mensah-Bonsu-blocked-passage-of-RTI-bill-George-Loh-635216"
urls_gw[311] <- "features/Samson-s-Take-RTI-law-will-kill-the-corrupt-pass-it-now-635174"
urls_gw[312] <- "NewsArchive/Parliament-committed-to-passing-RTI-Deputy-Speaker-assures-634968"
urls_gw[313] <- "NewsArchive/RTI-Coalition-charges-Akufo-Addo-to-redeem-promise-634323"
urls_gw[314] <- "politics/NDC-tackled-graft-Apaak-633108"
urls_gw[315] <- "business/Seminar-on-Ghana-s-RTI-bill-held-at-the-embassy-of-Ghana-in-Washington-DC-633103"
urls_gw[316] <- "NewsArchive/RTI-Bill-will-be-passed-before-Parliament-goes-on-recess-Akufo-Addo-632337"
urls_gw[317] <- "NewsArchive/Akufo-Addo-makes-a-strong-case-for-RTI-bill-passage-632029"
urls_gw[318] <- "NewsArchive/NPP-NDC-guilty-of-playing-political-football-with-RTI-Inusah-Fuseini-632159"
urls_gw[319] <- "NewsArchive/President-Akufo-Addo-sets-another-timeline-for-anti-corruption-missing-link-RTI-Bill-632004"
urls_gw[320] <- "NewsArchive/RTI-Bill-will-be-law-before-parliament-rises-Akufo-Addo-631940"
urls_gw[321] <- "NewsArchive/We-can-t-fight-corruption-by-denying-its-existence-NDC-630008"
urls_gw[322] <- "diaspora/ICPPF-Calls-on-Dr-Nduom-to-sign-the-Right-to-Information-Bill-139993"
urls_gw[323] <- "NewsArchive/RTI-Bill-will-be-passed-into-law-by-end-of-2018-Bawumia-629604"
urls_gw[324] <- "NewsArchive/Pass-RTI-bill-if-you-want-to-fight-corruption-MP-tells-Nana-Addo-628643"
urls_gw[325] <- "NewsArchive/Pass-RTI-Bill-to-do-away-with-perception-in-corruption-fight-Minority-627954"
urls_gw[326] <- "features/Right-to-Information-law-a-May-birth-626947"
urls_gw[327] <- "NewsArchive/Pass-RTI-Bill-to-show-commitment-to-corruption-fight-Minority-626878"
urls_gw[328] <- "NewsArchive/Ghana-Embassy-in-U-S-to-host-forum-on-RTI-bill-623331"
urls_gw[329] <- "NewsArchive/Press-Freedom-Day-without-RTI-Law-will-be-a-disgrace-MFWA-622829"
urls_gw[330] <- "NewsArchive/RTI-Bill-not-Parliament-s-priority-now-First-Deputy-Speaker-622644"
urls_gw[331] <- "NewsArchive/RTI-Bill-not-Parliament-s-priority-now-Osei-Wusu-622575"
urls_gw[332] <- "diaspora/Loud-Silence-Media-to-organize-RTI-bill-passage-forum-in-Washington-DC-622280"
urls_gw[333] <- "NewsArchive/Wean-yourselves-from-corruption-tag-CDD-to-Parliamentarians-622421"
urls_gw[334] <- "NewsArchive/CDD-Ghana-calls-on-Parliament-to-summon-A-G-Information-Minister-over-RTI-bill-621911"
urls_gw[335] <- "NewsArchive/IEA-mounts-pressure-on-government-to-pass-RTI-Bill-622168"
urls_gw[336] <- "NewsArchive/Pass-RTI-bill-to-help-fight-against-corruption-US-Ambassador-621804"
urls_gw[337] <- "NewsArchive/Journalists-not-interested-in-RTI-bill-GJA-620724"
urls_gw[338] <- "NewsArchive/Ghana-doesn-t-need-RTI-bill-Casely-Hayford-617304"
urls_gw[339] <- "NewsArchive/RTI-bill-NPP-and-NDC-are-all-cowards-Ace-Ankomah-617298"
urls_gw[340] <- "NewsArchive/Government-reiterates-commitment-to-pass-the-RTI-Bill-617044"
urls_gw[341] <- "NewsArchive/RTI-Bill-must-be-passed-for-Special-Prosecutor-to-be-effective-Asiedu-Nketia-617099"
urls_gw[342] <- "NewsArchive/Cabinet-yet-to-hold-talks-on-RTI-bill-Hamid-615585"
urls_gw[343] <- "NewsArchive/Pass-17-year-old-RTI-bill-CDD-Ghana-urges-government-615300"
urls_gw[344] <- "politics/NDC-was-not-interested-in-graft-fight-Braimah-614480"
urls_gw[345] <- "NewsArchive/Special-Prosecutor-will-struggle-without-RTI-bill-Asiedu-Nketia-614700"
urls_gw[346] <- "NewsArchive/RTI-Bill-still-not-ready-to-be-passed-into-law-Senior-Minister-606566"
urls_gw[347] <- "NewsArchive/Pass-RTI-Bill-urgently-as-done-for-Special-Prosecutor-Bill-Coalition-602491"
urls_gw[348] <- "features/Can-Special-Prosecutor-Bill-be-mere-semblance-of-commitment-to-fight-corruption-600995"
urls_gw[349] <- "NewsArchive/OccupyGhana-demands-timelines-for-passage-of-RTI-Bill-599588"
urls_gw[350] <- "features/Samson-s-Take-RTI-don-t-politicians-lie-when-they-claim-to-serve-citizens-599608"
urls_gw[351] <- "features/Executive-must-place-RTI-Bill-before-Parliament-without-any-further-delay-598679"
urls_gw[352] <- "NewsArchive/Stop-long-talk-and-pass-RTI-Bill-Group-charges-598130"
urls_gw[353] <- "NewsArchive/July-2018-latest-target-for-passage-of-RTI-Bill-596466"
urls_gw[354] <- "NewsArchive/Exert-pressure-on-Parliament-to-pass-RTI-into-law-Justice-Akoto-Bamfo-591991"
urls_gw[355] <- "NewsArchive/Diplomats-urged-to-press-Ghana-on-RTI-Bill-591554"
urls_gw[356] <- "NewsArchive/RTI-Coalition-wants-Geneva-to-push-Ghana-to-pass-Right-to-Information-Law-591547"
urls_gw[357] <- "features/Instruction-to-Ace-Bury-the-RTI-Bill-587960"
urls_gw[358] <- "NewsArchive/Without-RTI-Special-Prosecutor-s-Office-will-be-frustrated-Coalition-586382"
urls_gw[359] <- "NewsArchive/Absence-of-RTI-law-mockery-Anti-Corruption-Coalition-revives-call-586214"
urls_gw[360] <- "NewsArchive/June-3-twin-disaster-report-missing-as-Hosi-demands-passage-of-RTI-Bill-586208"
urls_gw[361] <- "NewsArchive/June-3-disaster-report-missing-as-Hosi-demands-passage-of-RTI-Bill-586010"
urls_gw[362] <- "NewsArchive/Senyo-Hosi-challenges-Akufo-Addo-to-pass-Right-to-Information-bill-586057"
urls_gw[363] <- "NewsArchive/RTI-bill-passage-necessary-for-accountability-iWatch-Africa-583547"
urls_gw[364] <- "features/Fighting-corruption-Will-Akufo-Addo-pass-the-test-his-predecessors-failed-571810"
urls_gw[365] <- "features/Are-we-okay-with-petty-and-huge-corruption-in-our-government-and-private-outfits-564484"
urls_gw[366] <- "NewsArchive/US-pledges-5m-to-fight-child-trafficking-in-Ghana-549262"
urls_gw[367] <- "NewsArchive/RTI-Bill-not-on-Parliament-s-agenda-as-it-reconvenes-for-second-sitting-542405"
urls_gw[368] <- "NewsArchive/Prosecute-public-officials-who-loot-State-money-Demonstrators-541885"
urls_gw[369] <- "NewsArchive/RTI-bill-goes-beyond-media-freedom-Oppong-Nkrumah-535486"
urls_gw[370] <- "NewsArchive/RTI-law-will-benefit-all-Ghanaians-Oppong-Nkrumah-535442"
urls_gw[371] <- "NewsArchive/Protect-reputations-Media-urged-534798"
urls_gw[372] <- "NewsArchive/Today-at-the-newsstands-534842"
urls_gw[373] <- "NewsArchive/Government-committed-to-passing-Right-to-Information-Bill-Hamid-534785"
urls_gw[374] <- "NewsArchive/Minority-blames-uncooperative-NPP-for-inability-to-pass-RTI-bill-in-2016-534774"
urls_gw[375] <- "NewsArchive/RTI-bill-will-be-passed-in-July-Mustapha-Hamid-534632"
urls_gw[376] <- "NewsArchive/World-Press-Freedom-Day-arrives-as-Right-to-Information-Bill-enters-9-year-talk-shop-534453"
urls_gw[377] <- "NewsArchive/100-days-of-change-under-President-Akufo-Addo-529468"
urls_gw[378] <- "NewsArchive/Expedite-passage-of-RTI-Bill-Coalition-to-government-525804"
urls_gw[379] <- "NewsArchive/RTI-Coalition-demands-Government-s-action-on-Right-To-Informational-bill-525920"
urls_gw[380] <- "NewsArchive/Contradictory-Akufo-Addo-has-shot-himself-in-the-foot-Odekro-520455"
urls_gw[381] <- "NewsArchive/More-MPs-as-minister-will-weaken-Parliament-s-leadership-Civil-Society-Group-520305"
urls_gw[382] <- "NewsArchive/We-ll-pass-RTI-bill-Ofori-Atta-515510"
urls_gw[383] <- "NewsArchive/We-ll-pass-RTI-bill-Ofori-Atta-515572"
urls_gw[384] <- "features/Fierce-tussle-over-government-cars-eye-opener-on-data-base-in-RTI-law-509435"
urls_gw[385] <- "NewsArchive/Bawumia-wants-Right-to-Information-Bill-passed-in-100-days-506253"
urls_gw[386] <- "NewsArchive/FLASHBACK-Mahama-bans-public-officials-from-buying-state-bungalows-499492"
urls_gw[387] <- "NewsArchive/Passage-of-RTI-Bill-must-be-accelerated-Felix-Owusu-Agyapong-499370"
urls_gw[388] <- "NewsArchive/11th-hour-attempt-to-pass-RTI-Bill-a-joke-Emile-Short-498911"
urls_gw[389] <- "NewsArchive/Minority-Leader-slams-Parliament-over-rushed-bills-499064"
urls_gw[390] <- "NewsArchive/Parliament-fails-to-pass-RTI-Bill-despite-Mahama-s-appeal-499012"
urls_gw[391] <- "NewsArchive/Mahama-begs-Parliament-to-approve-RTI-Bill-at-the-11th-hour-498862"
urls_gw[392] <- "NewsArchive/Mahama-s-RTI-wish-will-be-difficult-to-honor-Muntaka-498856"
urls_gw[393] <- "NewsArchive/Pass-RTI-bill-before-dissolution-Mahama-pleads-498788"
urls_gw[394] <- "features/Democratizing-information-in-Ghana-The-lack-thereof-497858"
urls_gw[395] <- "features/It-ain-t-gonna-happen-under-Mahama-of-Bole-497142"
urls_gw[396] <- "NewsArchive/Feature-RTI-Bill-is-needed-to-curb-corruption-in-the-country-497054"
urls_gw[397] <- "NewsArchive/Parliament-ends-last-session-without-passage-of-RTI-Bill-496707"
urls_gw[398] <- "NewsArchive/Speaker-can-t-determine-what-Parliament-will-do-Minority-Leader-496607"
urls_gw[399] <- "NewsArchive/NPP-sudden-opposition-to-RTI-bill-absurd-shameless-pathetic-Ayenini-496293"
urls_gw[400] <- "NewsArchive/Parliament-races-against-time-to-pass-RTI-bill-others-496423"
urls_gw[401] <- "NewsArchive/Speaker-of-parliament-doesn-t-determine-what-Parliament-will-do-Minority-Leader-496426"
urls_gw[402] <- "NewsArchive/We-are-not-dragging-our-feet-on-RTI-bill-Minority-496318"
urls_gw[403] <- "NewsArchive/We-will-boycott-last-minute-agreements-Minority-threatens-496363"
urls_gw[404] <- "NewsArchive/We-ll-cause-financial-loss-to-the-State-if-we-fail-to-pass-RTI-Bill-into-law-Bagbin-496254"
urls_gw[405] <- "NewsArchive/Minority-delaying-passage-of-RTI-Bill-Majority-496098"
urls_gw[406] <- "NewsArchive/I-ve-already-packed-my-things-from-my-office-Speaker-of-Parliament-495822"
urls_gw[407] <- "NewsArchive/President-Mahama-s-encounter-with-GBC-488285"
urls_gw[408] <- "features/Trump-Triumphs-Good-or-bad-riddance-for-Ghana-487219"
urls_gw[409] <- "NewsArchive/RTI-Coalition-dismayed-over-failure-to-pass-bill-486425"
urls_gw[410] <- "NewsArchive/Expedite-action-on-RTI-Bill-AG-to-Parliament-482534"
urls_gw[411] <- "NewsArchive/RTI-bill-passage-urgent-Dominic-Ayine-481072"
urls_gw[412] <- "NewsArchive/Government-withdraws-RTI-bill-478878"
urls_gw[413] <- "politics/NPP-deliberately-hampering-passage-of-RTI-bill-for-political-gains-NDC-477995"
urls_gw[414] <- "NewsArchive/We-are-determined-to-pass-RTI-Bill-into-law-Bagbin-476678"
urls_gw[415] <- "NewsArchive/Group-pickets-parliament-over-RTI-bill-476520"
urls_gw[416] <- "features/Feature-Our-public-advocates-and-intellectuals-failing-this-country-473964"
urls_gw[417] <- "features/Our-public-advocates-and-public-intellectuals-failing-this-country-473845"
urls_gw[418] <- "features/Our-public-advocates-and-public-intellectuals-failing-this-country-473696"
urls_gw[419] <- "NewsArchive/Mahama-can-be-frustrated-but-cannot-control-Parliament-Muntaka-473115"
urls_gw[420] <- "NewsArchive/Mahama-s-frustration-over-RTI-Bill-hypocritical-Minority-473156"
urls_gw[421] <- "NewsArchive/I-don-t-know-where-the-RTI-Bill-is-Mahama-472663"
urls_gw[422] <- "NewsArchive/Pass-RTI-bill-as-farewell-legacy-for-Ghanaians-CSO-145750"
urls_gw[423] <- "NewsArchive/Group-slams-Mahama-for-delaying-passage-of-RTI-Bill-472482"
urls_gw[424] <- "NewsArchive/Mahama-not-shown-commitment-Coalition-472018"
urls_gw[425] <- "politics/State-how-you-ll-fight-corruption-in-manifesto-GII-461783"
urls_gw[426] <- "NewsArchive/Fight-against-corruption-meaningless-without-RTI-bill-IEA-460137"
urls_gw[427] <- "NewsArchive/Greed-cause-of-unbridled-corruption-IEA-460022"
urls_gw[428] <- "NewsArchive/Government-not-responsible-for-delay-in-passing-RTI-Bill-MP-459265"
urls_gw[429] <- "NewsArchive/Pass-right-to-information-bill-before-elections-Vitus-Azeem-459243"
urls_gw[430] <- "NewsArchive/Parliament-has-lost-interest-in-RTI-Bill-Coalition-alleges-458889"
urls_gw[431] <- "NewsArchive/Coalition-angry-with-government-parliament-over-RTI-Bill-s-delay-458696"
urls_gw[432] <- "NewsArchive/Failure-to-pass-RTI-Bill-means-Mahama-NDC-cannot-be-trusted-Coalition-458790"
urls_gw[433] <- "features/Is-Parliament-and-government-really-not-ready-to-pass-the-RTI-bill-this-year-455915"
urls_gw[434] <- "features/Reluctance-to-pass-RTI-bill-worrying-455940"
urls_gw[435] <- "NewsArchive/Is-the-RTI-Bill-a-priority-Coalition-asks-452949"
urls_gw[436] <- "NewsArchive/RTI-bill-will-be-passed-by-July-441011"
urls_gw[437] <- "NewsArchive/Week-at-a-glance-Police-shake-up-Parliament-back-from-recess-EC-shocker-440598"
urls_gw[438] <- "NewsArchive/RTI-Bill-Exemption-clause-needed-Ayariga-440368"
urls_gw[439] <- "NewsArchive/RTI-Law-Implementation-challenges-ahead-Manteaw-440251"
urls_gw[440] <- "NewsArchive/Implementation-of-RTI-Law-will-be-challenging-Manteaw-440068"
urls_gw[441] <- "NewsArchive/Parliament-divided-over-Clause-1-of-RTI-Bill-439808"
urls_gw[442] <- "NewsArchive/RTI-law-to-change-political-culture-Akoto-Ampaw-439646"
urls_gw[443] <- "NewsArchive/Anti-graft-campaigners-to-monitor-Mahama-s-commitments-439000"
urls_gw[444] <- "features/What-Mr-president-should-be-telling-the-world-438713"
urls_gw[445] <- "features/Tarzan-asks-To-serve-or-to-loot-438167"
urls_gw[446] <- "NewsArchive/What-Mahama-should-be-telling-the-world-on-anti-corruption-438250"
urls_gw[447] <- "NewsArchive/GJA-clamours-for-RTI-bill-passage-435018"
urls_gw[448] <- "NewsArchive/RTI-bill-may-be-passed-next-year-George-Loh-433211"
urls_gw[449] <- "features/Human-rights-court-backs-Right-to-information-in-Ghana-431280"
urls_gw[450] <- "NewsArchive/High-court-s-full-disclosure-ruling-not-substitute-for-RTI-Lawyer-430909"
urls_gw[451] <- "regional/Gov-ts-urged-to-create-enabling-environment-for-media-424764"
urls_gw[452] <- "NewsArchive/RTI-MPs-admit-pressure-is-mounting-on-them-to-pass-Bill-422208"
urls_gw[453] <- "NewsArchive/We-re-not-scared-of-passing-RTI-Bill-MP-420120"
urls_gw[454] <- "politics/NDC-s-oil-and-gas-policy-promises-greater-transparency-417487"
urls_gw[455] <- "politics/Energy-policy-likely-to-fast-track-RTI-passage-417534"
urls_gw[456] <- "features/Let-s-follow-best-practices-and-leadership-on-Right-to-Information-Law-393181"
urls_gw[457] <- "politics/Right-to-Information-Bill-to-be-passed-next-year-393025"
urls_gw[458] <- "NewsArchive/Information-Bill-won-t-transform-media-landscape-Mahama-387028"
urls_gw[459] <- "features/Not-in-defense-of-the-judges-not-even-my-bro-385017"
urls_gw[460] <- "features/NPP-MP-Hammond-Wants-52B-Not-62B-for-Ghana-2-378423"
urls_gw[461] <- "NewsArchive/C-ttee-kicks-against-provision-in-RTI-Bill-366656"
urls_gw[462] <- "NewsArchive/Parliament-wants-RTI-Bill-to-cover-private-firms-365976"
urls_gw[463] <- "politics/Coalition-urges-Parliament-to-pass-bill-336938"
urls_gw[464] <- "NewsArchive/Professional-groups-demand-passage-of-RTI-into-law-335151"
urls_gw[465] <- "regional/Citizens-call-for-the-passage-of-RTI-Bill-into-Law-332821"
urls_gw[466] <- "features/Ghana-s-Rotten-Legal-System-330065"
urls_gw[467] <- "regional/Simli-Radio-to-educate-citizens-on-rights-324057"
urls_gw[468] <- "regional/Community-broadcasters-want-RTI-Bill-passed-323221"
urls_gw[469] <- "entertainment/Pass-Right-To-Information-Bill-Ghana-Community-Radio-Network-322802"
urls_gw[470] <- "NewsArchive/Pass-right-to-information-bill-GCRN-322538"
urls_gw[471] <- "features/Right-To-Info-Law-will-enhance-Ghana-s-democratic-image-315918"
urls_gw[472] <- "regional/Speaker-RTI-coalition-lock-horns-on-right-to-information-law-315914"
urls_gw[473] <- "regional/AU-Special-Rapporteur-interacts-on-RTI-Bill-315416"
urls_gw[474] <- "politics/African-Union-Special-Rapporteur-to-visit-Ghana-315059"
urls_gw[475] <- "politics/Ghana-requires-information-law-to-trace-looted-money-314801"
urls_gw[476] <- "NewsArchive/Pass-the-RTI-Bill-World-Bank-310828"
urls_gw[477] <- "NewsArchive/Coalition-punches-holes-in-RTI-bill-305332"
urls_gw[478] <- "features/Parliament-Must-Pass-the-Right-to-Information-RTI-Bill-302444"
urls_gw[479] <- "NewsArchive/RTI-Bill-can-t-stand-test-of-time-Prof-Karikari-301344"
urls_gw[480] <- "politics/Parliament-not-committed-to-reviewing-RTI-Bill-Coalition-301109"
urls_gw[481] <- "features/678-vs-692-Presidential-Staffers-300831"
urls_gw[482] <- "features/Corruption-In-Ghana-2001-2008-293097"
urls_gw[483] <- "features/Corruption-in-Ghana-Jan-2009-to-Nov-2013-292156"
urls_gw[484] <- "NewsArchive/Mahama-bans-public-officials-from-buying-state-bungalows-292131"
urls_gw[485] <- "politics/RTI-not-to-hound-politicians-289211"
urls_gw[486] <- "NewsArchive/Pass-an-effective-RTI-Bill-CHRI-tells-gov-t-287338"
urls_gw[487] <- "politics/Stop-political-rhetoric-pass-RTI-Bill-CSO-287310"
urls_gw[488] <- "regional/Rectify-anomalies-in-RTI-Bill-NGO-283548"
urls_gw[489] <- "features/Where-is-the-Freedom-of-Information-Bill-at-280925"
urls_gw[490] <- "regional/RTI-Bill-GJA-calls-for-an-independent-implementation-c-ssion-280673"
urls_gw[491] <- "politics/Dismiss-misconceptions-on-the-RTI-Law-CHRI-278567"
urls_gw[492] <- "regional/BIA-hails-Cabinet-approval-of-RTI-Bill-277097"
urls_gw[493] <- "politics/Honour-promise-RTI-Coalition-urges-President-275938"
urls_gw[494] <- "regional/Coalition-on-RTI-uncertain-about-viability-of-new-pension-scheme-272691"
urls_gw[495] <- "regional/Pass-RTI-act-to-make-public-private-sector-accountable-267219"
urls_gw[496] <- "regional/Parliament-urged-to-amend-RTI-Bill-264817"
urls_gw[497] <- "politics/Parliament-reminded-of-obligation-to-pass-RTI-into-law-253109"
urls_gw[498] <- "regional/Eastern-Regional-Coalition-demands-passage-of-RTI-252639"
urls_gw[499] <- "regional/Right-to-Information-Day-marked-in-Cape-Coast-251739"
urls_gw[500] <- "politics/Network-calls-for-passage-of-bill-244018"
urls_gw[501] <- "politics/Civil-Society-intensify-pressure-on-legislature-to-pass-RTI-Bill-242518"
urls_gw[502] <- "politics/NGOs-calls-on-government-to-expedite-action-on-the-passage-of-RTI-bill-241919"
urls_gw[503] <- "regional/National-Conference-on-Right-to-Information-slated-for-June-20-241680"
urls_gw[504] <- "politics/Coalition-on-Right-to-Information-denies-slowing-legislative-process-239695"
urls_gw[505] <- "politics/Ghana-Aid-Effectiveness-Forum-questions-delay-in-passing-RTI-Bill-239674"
urls_gw[506] <- "politics/Parliament-called-upon-to-expedite-action-on-Passage-of-RTI-Bill-239283"
urls_gw[507] <- "politics/Avoka-says-RTI-Bill-is-important-to-Parliament-239081"
urls_gw[508] <- "politics/Parliament-blamed-for-failing-to-pass-RTI-bill-237783"
urls_gw[509] <- "regional/Coalition-on-Right-to-Information-unhappy-with-Parliament-237544"
urls_gw[510] <- "features/What-is-holding-the-passage-of-the-RTI-Bill-220466"
urls_gw[511] <- "features/What-is-holding-the-passage-of-the-RTI-Bill-220364"
urls_gw[512] <- "politics/CPP-advocates-expansion-of-RTI-218002"
urls_gw[513] <- "features/Civil-Society-Faults-Ghana-s-Right-To-Information-Bill-216163"
urls_gw[514] <- "religion/Chieftaincy-must-be-part-of-agencies-covered-by-RTI-Bill-215693"
urls_gw[515] <- "features/Right-To-Information-a-necessary-tool-for-democracy-212389"
urls_gw[516] <- "features/RTI-a-tool-for-Environmental-Protection-189387"
urls_gw[517] <- "regional/Right-to-Information-advocates-attend-workshop-in-Wa-188787"
urls_gw[518] <- "NewsArchive/Coalition-calls-for-speedy-passage-of-RTI-Bill-to-Law-188699"
urls_gw[519] <- "NewsArchive/Liberia-sets-the-pace-for-Ghana-by-passing-RTI-Bill-187385"
urls_gw[520] <- "features/The-Ghanaian-Condition-Part-9-181809"
urls_gw[521] <- "features/The-Ghanaian-Condition-Part-9-181693"
urls_gw[522] <- "NewsArchive/Civil-Society-Organisation-launches-critique-on-RTI-Bill-145837"
urls_gw[523] <- "NewsArchive/Ampaw-Portions-of-RTI-bill-could-suppress-freedom-of-expression-181123"
urls_gw[524] <- "NewsArchive/Passage-of-RTI-Bill-will-help-curb-corruption-Devarajan-178584"
urls_gw[525] <- "NewsArchive/Parliament-asked-to-review-deadline-for-submission-of-RTI-memoranda-177414"
urls_gw[526] <- "NewsArchive/Thousand-man-march-for-Accra-to-push-RTI-175469"
urls_gw[527] <- "NewsArchive/Togolese-Paedophile-jailed-20-years-171809"
urls_gw[528] <- "NewsArchive/Coalition-commends-government-for-commitment-to-pass-RTI-Bill-171590"
urls_gw[529] <- "NewsArchive/Media-Foundation-commends-government-162998"
urls_gw[530] <- "NewsArchive/RTI-Bill-laid-before-Cabinet-162182"
urls_gw[531] <- "features/Mills-Rawlings-NDC-on-Track-to-Passing-NPP-Dud-of-RTI-Bill-161870"
urls_gw[532] <- "NewsArchive/Parliament-gets-ready-for-RTI-Bill-161547"
urls_gw[533] <- "NewsArchive/Government-intensifies-discussion-on-RTI-Bill-160680"
urls_gw[534] <- "features/Public-information-belongs-to-the-people-Give-it-out-160312"
urls_gw[535] <- "features/Mould-Iddrisu-is-jiving-re-Freedom-of-Information-bill-159649"
urls_gw[536] <- "NewsArchive/RTI-is-bulwark-against-corruption-Lawyer-159555"
urls_gw[537] <- "NewsArchive/Ninth-Annual-Constitution-Week-celebration-commences-on-April-28-158363"
urls_gw[538] <- "NewsArchive/Kufuor-exhibited-lack-of-political-will-to-pass-RTI-156316"
urls_gw[539] <- "NewsArchive/Ghana-marks-Right-to-Know-Day-on-September-28-150582"
urls_gw[540] <- "features/Pass-the-FOI-not-RTI-Bill-Now-NPP-Nana-Akufo-Addo-146420"
urls_gw[541] <- "NewsArchive/NPP-to-fast-track-passage-of-Right-to-Information-Bill-146009"
urls_gw[542] <- "NewsArchive/AG-explains-RTI-145838"
